CREATE DATABASE IF NOT EXISTS smeagol;

ALTER DATABASE smeagol
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON smeagol.* TO pc@localhost IDENTIFIED BY 'pc';

USE smeagol;

CREATE TABLE IF NOT EXISTS quotes (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(255));

CREATE DATABASE IF NOT EXISTS gollum;

ALTER DATABASE gollum
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON gollum.* TO pc@localhost IDENTIFIED BY 'pc';

USE gollum;

CREATE TABLE IF NOT EXISTS quotes (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(255));